name: Fleet Model Test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop, release/**]

permissions: 
    pull-requests: read
    contents: read
    actions: read
    checks: read

concurrency:
  group: ${{ github.event.pull_request.number }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.pull_request.number || '0' }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  work_dir: /paddle
  PADDLE_ROOT: /paddle
  ci_scripts: /paddle/ci
  BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}
  CI_name: fleet-model-test
  no_proxy: "bcebos.com,.bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"
  docker_image: "ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:ubuntu24-cuda129-py312-dev"

defaults:
  run:
    shell: bash

jobs:
  check-bypass:
    name: Check bypass
    if: ${{ inputs.can-skip != 'true' }}
    uses: ./.github/workflows/check-bypass.yml
    with:
      workflow-name: 'fleet-model-test'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      
  
  check_documents_type:
    needs: check-bypass
    if: ${{ needs.check-bypass.outputs.can-skip == 'false' }}
    name: check documents type for pull request
    runs-on:
      group: APPROVAL
    env:
      GITHUB_REPO_NAME: ${{ github.repository }}
    outputs:
      is_md_only: ${{ steps.check_files.outputs.is_md_only }}
    steps:
      - name: Cleanup
        run: |
          rm -rf * .[^.]*
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: git diff and check 
        id: check_files
        if: |
          github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'fleet-models-ci')
        run: |
          changed_files=$(git diff origin/${{ github.event.pull_request.base.ref }}...HEAD --name-only)
          echo "Changed files: $changed_files"
          all_count=0
          md_count=0
          for file in $changed_files; do
            all_count=$((all_count+1))
            echo $file
            if [[ $file == *.md ]]; then
              echo "Markdown document: $file has been changed."
              md_count=$((md_count+1))
            fi
          done
          echo "总计: all_count=$all_count, md_count=$md_count"
          if [ "$md_count" -eq "$all_count" ]; then
            echo "is_md_only=true" >> $GITHUB_OUTPUT
            echo "is_md_only=true"
          else
            echo "is_md_only=false" >> $GITHUB_OUTPUT
            echo "is_md_only=false"
          fi
          echo "is_md_only: $(cat $GITHUB_OUTPUT | grep is_md_only || echo '未找到')"
    
  integration-test-H20-single-card:
    needs: [check_documents_type, check-bypass]
    if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' && needs.check-bypass.outputs.can-skip == 'false' }}
    name: Integration test (H20, single card)
    runs-on:
      group: Fleet-H-single-card
    env:
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-single-card
    steps:
      - name: Determine the runner
        run: |
          gpu_id=$(( $(echo $PWD | awk -F'/' '{print $3}' | awk -F'-' '{print $2}') - 1 ))
          echo GPU_DEVICES="$gpu_id" >> $GITHUB_ENV

      - name: Check docker image and run container
        env:
          GPU_DEVICES: ${{ env.GPU_DEVICES }}
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker pull $docker_image
          set -x
          docker run -d -t --name ${container_name} --gpus "\"device=${GPU_DEVICES}\"" --shm-size=32G \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}/../../..:/root \
            -v /ssd1/paddle-1/action_cache:/home/.cache \
            -v ${{ github.workspace }}:/workspace \
            -e BRANCH \
            -e PR_ID \
            -e COMMIT_ID \
            -e PADDLE_ROOT \
            -e ci_scripts \
            -e CACHE_DIR \
            -e no_proxy \
            -e CI_name \
            -e PIP_CACHE_DIR \
            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
            -e GITHUB_REPO_NAME="${{ github.repository }}" \
            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_RUN_ID="${{ github.run_id }}" \
            -e PR_USER="${{ github.event.pull_request.user.login }}" \
            -w /workspace --network host ${docker_image}

      - name: Install PaddleFormers
        id: formers_install
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          rm -rf * .[^.]*
          echo $PR_USER
          source /root/proxy
          mkdir -p /home/.cache/pip
          pip cache dir
          pip install --upgrade pip
          git clone https://github.com/PaddlePaddle/PaddleFormers.git -b ${BRANCH}
          cd PaddleFormers
          git status
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git pull --no-edit origin pull/${PR_ID}/head
          export UV_SKIP_WHEEL_FILENAME_CHECK=1
          fleet_commit=$(python scripts/ci_utils/get_fleet_commit.py)
          git clone https://github.com/PaddlePaddle/PaddleFleet.git
          cd PaddleFleet
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git checkout release/0.4
          git reset --hard $fleet_commit
          CUDA_VERSION=CUDA129 scripts/install_ops_wheel.sh
          cd ..
          # python -m pip install --pre  paddlefleet-ops --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install -e ".[paddlefleet]" --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          wget -q --no-proxy https://paddle-qa.bj.bcebos.com/paddleformers/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          echo "paddle commit:"
          python -c "import paddle; print(paddle.version.commit)"
          echo "paddlefleet commit:"
          python -c "import paddlefleet; print(paddlefleet.version.commit)"
          cd /workspace
          wget -q --no-proxy -O bos_new.tar.gz https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar xf bos_new.tar.gz -C bos
          pip install bce-python-sdk==0.8.74
          pip install coverage==7.6.1
          pip install librosa==0.11.0
          '

      - name: Proprocess for integration test
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/preprocess.sh
          preprocess_exit_code=$?
          if [[ "$preprocess_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mPreprocess failed.\033[0m"
            exit 1
          else
            echo -e "\033[32mPreprocess succeeded.\033[0m"
          fi
          '


      - name: Integration test (GLM4.5 single-card)
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45_single single_pt
          glm45_single_card_exit_code=$?
          if [[ "$glm45_single_card_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 single-card.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 single-card.\033[0m"
          fi
          '

      - name: Integration test (Qwen3-30B-A3B single-card)
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen_single single_pt
          qwen3_single_card_exit_code=$?
          if [[ "$qwen3_single_card_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: Qwen3-30B-A3B single-card.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: Qwen3-30B-A3B single-card.\033[0m"
          fi
          '

      - name: Qwen3-vl-8k-single-card
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl_single single_sft
          exit_code=$?
          if [[ "$exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: Qwen3-vl-8k-single-card.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: Qwen3-vl-8k-single-card.\033[0m"
          fi
          '


      - name: Terminate and delete the container
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}


  integration-test-H20-multi-card:
    needs: [check_documents_type, check-bypass]
    if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' && needs.check-bypass.outputs.can-skip == 'false' }}
    name: Integration test (H20, multi-card)
    runs-on:
      group: Fleet-H-multi-card
    env:
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-multi-card
    steps:
      - name: Check docker image and run container
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker pull $docker_image
          docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}/../../..:/root \
            -v /ssd1/paddle-1/action_cache:/home/.cache \
            -v ${{ github.workspace }}:/workspace \
            -e BRANCH \
            -e PR_ID \
            -e COMMIT_ID \
            -e PADDLE_ROOT \
            -e ci_scripts \
            -e CACHE_DIR \
            -e no_proxy \
            -e CI_name \
            -e PIP_CACHE_DIR \
            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
            -e GITHUB_REPO_NAME="${{ github.repository }}" \
            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_RUN_ID="${{ github.run_id }}" \
            -e PR_USER="${{ github.event.pull_request.user.login }}" \
            -w /workspace --network host ${docker_image}


      - name: Install PaddleFormers
        id: formers_install
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          rm -rf * .[^.]*
          source /root/proxy
          mkdir -p /home/.cache/pip
          pip cache dir
          pip install --upgrade pip
          git clone https://github.com/PaddlePaddle/PaddleFormers.git  -b ${BRANCH}
          cd PaddleFormers
          git status
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git pull --no-edit origin pull/${PR_ID}/head
          export UV_SKIP_WHEEL_FILENAME_CHECK=1
          fleet_commit=$(python scripts/ci_utils/get_fleet_commit.py)
          git clone https://github.com/PaddlePaddle/PaddleFleet.git
          cd PaddleFleet
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git checkout release/0.4
          git reset --hard $fleet_commit
          CUDA_VERSION=CUDA129 scripts/install_ops_wheel.sh
          cd ..
          # python -m pip install --pre  paddlefleet-ops --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install -e ".[paddlefleet]" --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          # wget -q --no-proxy --no-check-certificate https://paddle-github-action.cdn.bcebos.com/PaddleFleet/release/0.2/latest/cu129/paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl
          # pip uninstall paddlefleet -y
          # pip install paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu129/
          # wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Release-TagBuild-Training-Linux-Gpu-Cuda12.9-Cudnn9.9-Trt10.5-Mkl-Avx-Gcc11-SelfBuiltPypiUse/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          # pip uninstall paddlepaddle-gpu -y
          # pip install paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          wget -q --no-proxy https://paddle-qa.bj.bcebos.com/paddleformers/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          echo "paddle commit:"
          python -c "import paddle; print(paddle.version.commit)"
          echo "paddlefleet commit:"
          python -c "import paddlefleet; print(paddlefleet.version.commit)"
          cd /workspace
          wget -q --no-proxy -O bos_new.tar.gz https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar xf bos_new.tar.gz -C bos
          pip install bce-python-sdk==0.8.74
          pip install coverage==7.6.1
          pip install librosa==0.11.0
          '
      
      - name: GLM4.5 pre-train
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 pt
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
          fi
          '

      - name: GLM4.5 sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 sft
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 sft.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 sft.\033[0m"
          fi
          '
      
      - name: GLM4.5 sft cp
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 sft_cp
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 sft cp.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 sft cp.\033[0m"
          fi
          '
      
      - name: GLM4.5 lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 lora
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 lora.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 lora.\033[0m"
          fi
          '
      
      - name: GLM4.5 dpo
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 dpo
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 dpo.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 dpo.\033[0m"
          fi
          '

      - name: GLM4.5 dpo_lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 dpo_lora
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 dpo lora.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 dpo lora.\033[0m"
          fi
          '
      - name: GLM4.5 pre-train (EP4)
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45_ep4 pt
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 EP4.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 EP4.\033[0m"
          fi
          '

      - name: GLM4.5 pre-train (FP8)
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45_fp8 pt
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 FP8.\033[0m"
          fi
          '

      - name: GLM4.5 pre-train (Grouped GEMM)
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45_grouped_gemm pt
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 Grouped GEMM.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 Grouped GEMM.\033[0m"
          fi
          '

      # - name: Gemma4 pre-train
      #   if: (success() || failure()) && steps.formers_install.conclusion == 'success'
      #   run: |
      #     docker exec -t ${{ env.container_name }} /bin/bash -ce '
      #     source /root/proxy
      #     timeout 20m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh gemma4 pt
      #     '

      - name: Qwen pre-train
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen pt
          '
        
      - name: Qwen sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen sft
          '


      - name: Qwen lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen lora
          '

      - name: Qwen vl sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl sft h20
          '
      
      - name: Qwen vl lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl lora h20
          '

      - name: Qwen vl moe
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 10m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl_moe sft h20
          '
      
      - name: Qwen3-vl-8k-fsdp
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 10m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl_fsdp sft h20
          '

      - name: Terminate and delete the container
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}
      

  integration-test-a100:
    needs: [check_documents_type, check-bypass]
    if: ${{ needs.check_documents_type.outputs.is_md_only == 'false' && needs.check-bypass.outputs.can-skip == 'false' }}
    name: Integration test (A100)
    runs-on:
      group: Distribute
    env:
      PIP_CACHE_DIR: /home/.cache/pip
      CACHE_DIR: /home/.cache
      TASK: formers-fleet-CI-${{ github.event.pull_request.number }}-integration-test-A100
    steps:
      - name: Check docker image and run container
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker pull $docker_image
          docker run -d -t --name ${container_name} --gpus all --shm-size=32G \
            -v "/dev/shm:/dev/shm"  \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}/../../..:/root \
            -v /ssd1/paddle-1/action_cache:/home/.cache \
            -v ${{ github.workspace }}:/workspace \
            -e BRANCH \
            -e PR_ID \
            -e COMMIT_ID \
            -e PADDLE_ROOT \
            -e ci_scripts \
            -e CACHE_DIR \
            -e no_proxy \
            -e CI_name \
            -e PIP_CACHE_DIR \
            -e GITHUB_SHA="${{ github.event.pull_request.head.sha }}" \
            -e GITHUB_HEAD_REF="${{ github.head_ref }}" \
            -e GITHUB_BASE_SHA="${{ github.event.pull_request.base.sha }}" \
            -e GITHUB_REPO_NAME="${{ github.repository }}" \
            -e GITHUB_EVENT_NAME="${{ github.event_name }}" \
            -e GITHUB_EVENT_PULL_REQUEST_NUMBER="${{ github.event.pull_request.number }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_RUN_ID="${{ github.run_id }}" \
            -e PR_USER="${{ github.event.pull_request.user.login }}" \
            -w /workspace --network host ${docker_image}

      - name: Install PaddleFormers
        id: formers_install
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          rm -rf * .[^.]*
          source /root/proxy
          mkdir -p /home/.cache/pip
          pip cache dir
          pip install --upgrade pip
          git clone https://github.com/PaddlePaddle/PaddleFormers.git -b ${BRANCH}
          cd PaddleFormers
          git status
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git pull --no-edit origin pull/${PR_ID}/head
          export UV_SKIP_WHEEL_FILENAME_CHECK=1
          fleet_commit=$(python scripts/ci_utils/get_fleet_commit.py)
          git clone https://github.com/PaddlePaddle/PaddleFleet.git
          cd PaddleFleet
          git config --global --add safe.directory /workspace/PaddleFormers
          git config user.name "PaddleCI"
          git config user.email "paddle_ci@example.com"
          git config pull.rebase false
          git checkout release/0.4
          git reset --hard $fleet_commit
          CUDA_VERSION=CUDA129 scripts/install_ops_wheel.sh
          cd ..
          # python -m pip install --pre  paddlefleet-ops --index-url https://www.paddlepaddle.org.cn/packages/nightly/cu129/ --extra-index-url https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install -e ".[paddlefleet]" --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu129/ --extra-index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          # wget -q --no-proxy --no-check-certificate https://paddle-github-action.cdn.bcebos.com/PaddleFleet/release/0.2/latest/cu129/paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl
          # pip uninstall paddlefleet -y
          # pip install paddlefleet-0.0.0-cp310-cp310-linux_x86_64.whl --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu129/
          # wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Release-TagBuild-Training-Linux-Gpu-Cuda12.9-Cudnn9.9-Trt10.5-Mkl-Avx-Gcc11-SelfBuiltPypiUse/latest/paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl
          # pip uninstall paddlepaddle-gpu -y
          # pip install paddlepaddle_gpu-0.0.0-cp310-cp310-linux_x86_64.whl --index-url=https://www.paddlepaddle.org.cn/packages/nightly/cu129/
          echo "paddle commit:"
          python -c "import paddle; print(paddle.version.commit)"
          echo "paddlefleet commit:"
          python -c "import paddlefleet; print(paddlefleet.version.commit)"
          cd /workspace
          wget -q --no-proxy -O bos_new.tar.gz https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz --no-check-certificate
          mkdir bos
          tar xf bos_new.tar.gz -C bos
          pip install bce-python-sdk==0.8.74
          pip install coverage==7.6.1
          pip install librosa==0.11.0
          wget -q --no-proxy https://paddle-qa.bj.bcebos.com/paddleformers/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          '
          

      - name: GLM4.5 pre-train
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 pt a100
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5.\033[0m"
          fi
          '
        
      - name: GLM4.5 sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 sft a100
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 sft.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 sft.\033[0m"
          fi
          '
      
      - name: GLM4.5 lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 lora a100
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 lora.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 lora.\033[0m"
          fi
          '
      
      - name: GLM4.5 dpo
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 dpo a100
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 dpo.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 dpo.\033[0m"
          fi
          '
      
      - name: GLM4.5 dpo_lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh glm45 dpo_lora a100
          glm45_exit_code=$?
          if [[ "$glm45_exit_code" != "0" ]]; then
            echo -e "::error:: \033[31mIntegration test failed: GLM4.5 dpo lora.\033[0m"
            exit 1
          else
            echo -e "\033[32mIntegration test succeeded: GLM4.5 dpo lora.\033[0m"
          fi
          '

      - name: Qwen pre-train
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen pt a100
          '
        
      - name: Qwen sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen sft a100
          '

      - name: Qwen lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen lora a100
          '

      - name: Qwen vl sft
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl sft a100
          '
      
      - name: Qwen vl lora
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 5m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl lora a100
          '

          
      - name: Qwen vl moe
        if: (success() || failure()) && steps.formers_install.conclusion == 'success'
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -ce '
          source /root/proxy
          timeout 10m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl_moe sft a100
          '


      # - name: Qwen3-vl-8k-fsdp
      #   if: (success() || failure()) && steps.formers_install.conclusion == 'success'
      #   run: |
      #     docker exec -t ${{ env.container_name }} /bin/bash -ce '
      #     source /root/proxy
      #     timeout 10m bash -x PaddleFormers/tests/integration_test/run_fleet_cice.sh qwen3vl_fsdp sft h20
      #     '

      - name: Terminate and delete the container
        if: ${{ always() }}
        run: |
          set +e
          docker exec -t ${{ env.container_name }} /bin/bash -c 'rm -rf * .[^.]*'
          docker rm -f ${{ env.container_name }}